#
# Module manifest for module 'PowerProfile'
#
# Generated by: Julian Pawlowski
#
# Generated on: 12/14/2021
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PowerProfile.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '0600e670-afd2-4265-8b1e-ba37b3307916'

# Author of this module
Author = 'Julian Pawlowski'

# Company or vendor of this module
CompanyName = 'PowerProfile'

# Copyright statement for this module
Copyright = '(c) 2022 Julian Pawlowski. All rights reserved.'

# Description of the functionality provided by this module
Description = @'
A modern and cross-platform PowerShell profile, based on directories instead of pure files.
PowerProfile uses a directory structure for user profiles instead of single script files. It extends the native capabilities of PowerShell to also support profiles for individual terminal applications.

Visit https://PowerProfile.sh/ to learn more.
'@

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @(
    'PowerProfile.Core.Load.ps1'
)

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
ModuleList = @(
    '.\PowerProfile.Core.psd1'
)

# List of all files packaged with this module
#   ((((Get-ChildItem -File -Recurse).FullName) -Replace ([string]$PWD + ([System.IO.Path]::DirectorySeparatorChar)),"'.\") -replace '$',"'") -replace '/','\'
FileList = @(
    '.\PowerProfile.Core.Load.ps1'
    '.\PowerProfile.Core.psd1'
    '.\PowerProfile.Core.psm1'
    '.\PowerProfile.psd1'
    '.\PowerProfile.psm1'
    '.\profile.ps1'
    '.\PSProfile\Profile\0001.PoProfile-Validate PowerShell Package Management.Setup.ps1'
    '.\PSProfile\Profile\0001.PoProfile-Validate PowerShellGet.Setup.ps1'
    '.\PSProfile\Profile\Config\PoProfile-PSPackageManagement.config.psd1'
    '.\PSProfile\Profile\Config\PoProfile-PSPowerShellGet.config.psd1'
    '.\PSProfile\Profile\Config\Settings\PSReadline.Settings.psd1'
    '.\PSProfile\Profile\Config\Install-PSResource\PoProfile.Core.PSResource.psd1'
    '.\PSProfile\Profile\_Platform_NonWindows\Config\Settings\UnixCompleters.Settings.psd1'
    '.\PSProfile\Profile\_Platform_NonWindows\Config\Install-PSResource\PoProfile-Platform_NonWindows.PSResource.psd1'
    '.\PSProfile\Profile\Functions\prompt.Interactive.ps1'
    '.\PSProfile\EveryProfile\0020.PoProfile-Install PowerShell modules.Setup.ps1'
    '.\PSProfile\EveryProfile\0020.PoProfile-Install PowerShell scripts.Setup.ps1'
    '.\PSProfile\EveryProfile\0021.PoProfile-Install PowerShell resources.Setup.ps1'
    '.\PSProfile\EveryProfile\0030.PoProfile-Apply user settings.Hidden.ps1'
    '.\PSProfile\EveryProfile\_Platform_macOS\0010.PoProfile-Install Homebrew packages.Setup.NotElevated.ps1'
    '.\PSProfile\EveryProfile\_Platform_macOS\install-homebrew-packages.sh'
    '.\PSProfile\EveryProfile\_Platform_macOS\install-homebrew.sh'
    '.\en-US\about_PowerProfile.help.txt'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'PowerShell'
            'Profile'
            'PSProfile'
            'PoshProfile'
            'Environment'
            'OneDrive'
            'PSEdition_Desktop'
            'PSEdition_Core'
            'Windows'
            'Linux'
            'MacOS'
            'PowerProfile'
        )

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/PowerProfile/PowerProfile/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://PowerProfile.sh/'

        # A URL to an icon representing this module.
        IconUri = 'https://avatars.githubusercontent.com/u/95570306'

        # ReleaseNotes of this module
        ReleaseNotes = @'
This is preview version of the upcoming PowerProfile first public release.

Please report any bugs or feature requests to our GitHub site:
https://github.com/PowerProfile/PowerProfile
'@

        # Prerelease string of this module
        Prerelease = 'alpha.4'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $false

        # External dependent modules of this module
        ExternalModuleDependencies = @(
            'PowerProfile.Commands'
        )

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
